#!/bin/zsh

SRC_PATH="/usr/local/bin/my-aws"
SELECTED_PATH="$HOME/.myaws/selected"
PROFILE_PATH="$HOME/.myaws/profile"
TEMP_PATH="$HOME/.myaws/temp"

source "$SRC_PATH/file-managment.sh"
source "$SRC_PATH/profile-logs.sh"
source "$SRC_PATH/s3upload.sh"

usage()
{
    echo "\033[1mDescription:\033[0m"
    echo "  This is a program to help make uploading files to aws s3 buckets easier"
    echo "  Running \"myaws create-log\" in the root"
    echo "  folder of the repo will create a log, removing the need to manauly add files"
    echo "  and specify the bucket each time. Instead, only the files"
    echo "  that have been changed since last upload will be uploaded again."
    echo ""
    echo "\033[1mUsage:\033[0m"
    echo "  myaws help                      displays help menu"
    echo "  myaws list                      displays all selected files"
    echo "  myaws profile                   set aws profile to be used"
    echo "  myaws create-log                creates a myaws record"
    echo "  myaws delete-log                deletes any logs setup in the directory"
    echo "  myaws add <file path>           adds a file or folder to being selected"
    echo "  myaws remove <file path>        removes a file or folder from being selected"
    echo "  myaws upload <option> <bucket>  uploads files to aws s3"
    echo "      options:"
    echo "          --selected              uploads files that are currently selected, view file with myaws list"
    echo "          --changes               uploads all files in current directory that have been changed since last upload"
    echo "      bucket:"
    echo "          Specify a s3 bucket to upload to using the format s3://bucket-path/"
    echo "          Or, if a myaws log has been created in the directory, no need to specify"
}

if ! [[ $# -gt 0 ]]; then
    usage
    exit 1
fi

program="$1"

case "$program" in

    "help"|"-h"|"--help")
        usage
        exit 0
    ;;

    "list")
        echo "selected files: "
        echo ""
        cat "$SELECTED_PATH"
        echo ""
        echo "You can add files using \"myaws add <file path>\""
        echo "and remove files using \"myaws remove <file path>\""
    ;;

    "profile")
        updateProfile
    ;;

    "add")
        if ! [[ $# -eq 2 ]]; then
            usage
            exit 1
        fi
        # call the appropriate function
        addFile "$2"
    ;;

    "remove")
        if ! [[ $# -eq 2 ]]; then
            usage
            exit 1
        fi
        # call the appropriate function
        removeFile "$2"
    ;;

    "upload")
        # check for to many or not enough args. Should be between 2-3 args
        if [[ $# -gt 3 ]] || [[ $# -eq 1 ]]; then
            usage
            exit 1
        fi

        if [[ "$2" == "--selected" ]]; then
            uploadOptionSelected "$3"
        elif [[ "$2" == "--changes" ]]; then
            uploadOptionChanged "$3"
        else
            usage
            exit 1
        fi
    ;;

    "create-log")
        if ! [[ $# -eq 1 ]]; then
            usage
            exit 1
        fi
        create-log
    ;;

    "delete-log")
        if ! [[ $# -eq 1 ]]; then
            usage
            exit 1
        fi
        delete-log
    ;;

    *)
        usage
        exit 1
    ;;
esac