#!/bin/zsh

readonly SRC_FILES="../src"
readonly INSTALLER_FILES="../installer"

readonly MAIN_DIR="$HOME/.myaws"
readonly SCRIPTS_DIR="$MAIN_DIR/scripts"
readonly USRFILES_DIR="$MAIN_DIR/usr-files"

readonly ZPROFILE="$HOME/.zprofile"
readonly PROFILE="$USRFILES_DIR/profile"

addfiles()
{
    mkdir -p "$MAIN_DIR"
    mkdir -p "$SCRIPTS_DIR"
    mkdir -p "$USRFILES_DIR"

    cp "$SRC_FILES/file-managment.sh" "$SCRIPTS_DIR"
    cp "$SRC_FILES/myaws" "$SCRIPTS_DIR"
    cp "$SRC_FILES/profile-logs.sh" "$SCRIPTS_DIR"
    cp "$SRC_FILES/s3upload.sh" "$SCRIPTS_DIR"

    touch "$USRFILES_DIR/temp"
    touch "$USRFILES_DIR/profile"
    touch "$USRFILES_DIR/selected"
    cp "$INSTALLER_FILES/defaultIgnoreFile" "$USRFILES_DIR/ignore"

    chmod g+w "$USRFILES_DIR/temp"
    chmod g+w "$USRFILES_DIR/profile"
    chmod g+w "$USRFILES_DIR/selected"
    chmod g+w "$USRFILES_DIR/ignore"
}

addPath()
{
    print "# Added by my-aws installer" >> "$ZPROFILE"
    print 'export PATH="$PATH:$HOME/.myaws/scripts"' >> "$ZPROFILE"
    print "" >> "$ZPROFILE"
}

echo "installing files ..."
addfiles
echo "updating paths ..."
addPath
echo "For any myaws upload commands to work, you must be signed into"
echo "aws cli with the same profile saved in myaws config, which you"
echo "can change at any time by running myaws profile."
echo -n "Enter profile to run aws cli commands with: "
read profileName
print "$profileName" > "$PROFILE"
echo "Installation and setup complete. Run myaws help to see full list of commands."
source "$ZPROFILE"
exit 0